version: '3.8'

services:

  web:
  # builda a imagem usando o Dockerfile na raiz do projeto
    build: .

    # Porta em que a aplicação esta rodando
    ports:
      - "5153:5153"

    # variaveis de ambiente referentes ao banco de dados
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}

    # não faz sentido esse serviço subir se o banco de dados não tiver subido antes, por isso adicionamos essa "dependência" ao outro serviço por segurança. Devido à condition, o serviço web só vai subir quando o serviço db estiver saudável. 
    depends_on:
          db:
            condition: service_healthy

    volumes:
      - .:/app

    networks:
      - app-network

  db:
  # usamos essa imagem, pois como é a mais recente, acredito ter mais suporte à funcionalidades mais novas do postgres, além de ser a mais atualizada em termos de segurança
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
    # comando para para verificar se o postgres está pronto para receber conexões
      test: pg_isready -U postgres -d ${DB_NAME}
      # tempo entre cada tentativa de verificação
      interval: 5s
      # tempo limite que o comando 'pg_isready' tem para responder antes de ser considerado uma falha
      timeout: 5s
      # falhas consecutivas permitidas antes de definir o banco como "doente"
      retries: 5
      # tempo para o banco criar os arquivos antes de começar analisa-lo
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql

    networks:
      - app-network

# nessa configuração, deixamos a rede explicitamente em bridge (ponte) para garantir que ambos os serviços se comuniquem
networks:
  app-network:
    driver: bridge

# persistencia do banco de dados usando volumes
volumes:
  postgres_data: